### ISSUE TITLE
Can't track duration below 1:00 hour

### ISSUE THREAD

**Issue by th-at-ds** [digitalservicebund/achill#7]
1. Open https://track-your-time.dev.ds4g.net/projects
2. Type "0:30" in "Hours" 
3. Type "Onbaord new designer" in "What"
4. Click "Add"
5. Actual result: See red outline in "Hours" input field

Expected result: See confirmation of accepted input.

Improvement idea: Display error message on outlined input field for the user to help themselves.

<img width="814" alt="Bildschirmfoto 2022-06-20 um 17 44 59" src="https://user-images.githubusercontent.com/107873358/174638158-dac06cbc-d2a0-4abb-9da2-863b297ec8db.png">

**Comment by chrkaatz** [comment]
One fix would be to put 0.5 but I will add a fix for this case as well :-)
