### ISSUE TITLE
Date picker set to last entered date by default

### ISSUE THREAD

**Issue by th-at-ds** [digitalservicebund/achill#8]
1. Open https://track-your-time.dev.ds4g.net/projects
2. Click "Date"
4. Actual result: See date picker with last selected date as default

Expected result: See current date as default date

<img width="448" alt="Bildschirmfoto 2022-06-20 um 17 58 25" src="https://user-images.githubusercontent.com/107873358/174640513-14d1a94c-d124-4343-b138-30537ea95257.png">

**Comment by HendrikSchmidt** [comment]
There is no date-picker any longer.
