### ISSUE TITLE
Booking on "closed" position does not show error

### ISSUE THREAD

**Issue by weilbith** [digitalservicebund/achill#9]
Hey 👋🏾 

first of all, thank you very much for this nice tool! 🙏🏾 

And here is my story:
I picked the wrong position in Troi as a favorite to book hours for. But the position is already closed (fulfilled "Einzelauftrag"). As I was unfamiliar with the tool, I was booking hours continuously, without noticing they don't actually got added. I didn't know that they should pop-up in list below the input form. So every time I clicked on `add` the input fields got cleared, but nothing happened.
Would be maybe nice to get an error here? Or is there an error and I didn't notice?

**Comment by HendrikSchmidt** [comment]
`isInvoiced` is now taken into consideration: https://github.com/digitalservicebund/achill/commit/f9af43ed2da6e6ccee9057a3a6a8ed9216c5835d
